FROM dalogik/qt-docker:qt6.10.0-win64-mingw AS base-img

LABEL version="0.3-win"

# Install additional required packages
RUN \
    apt-get update \
    && apt-get install -y --no-install-suggests --no-install-recommends \
    ca-certificates git \
    && rm -rf /var/lib/apt/lists/*
