FROM dalogik/qt-docker:qt6.11.0-win64-mingw AS base-img

LABEL version="0.2-win"

# Install additional required packages
RUN \
    apt-get update \
    && apt-get install -y --no-install-suggests --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*
