name: Build Application

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d06alexandrov/u-scope:0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build an Application
        run: |
          cmake -B build
          cmake --build build --config Release --target u-scope

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: u-scope-app
          path: build/source/u-scope
