name: Build Application

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  app-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platforms: [ {os: 'linux', tag: '0.5'}, {os: 'windows', tag: '0.4-win'}]
    container:
      image: ghcr.io/d06alexandrov/u-scope:${{ matrix.platforms.tag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Linux Application
        if: matrix.platforms.os == 'linux'
        run: |
          cmake -B build
          cmake --build build --config Release --target u-scope

      - name: Build Windows Application
        if: matrix.platforms.os == 'windows'
        run: |
          # Create a directory Wine can own
          mkdir -p /tmp/wineprefix
          export WINEPREFIX=/tmp/wineprefix
          # Build
          cmake -B build -G Ninja
          cmake --build build --config Release --target u-scope
          cmake --install build --config Release --prefix $GITHUB_WORKSPACE/u-scope-win64

      - name: Upload Linux artifacts
        if: matrix.platforms.os == 'linux'
        uses: actions/upload-artifact@v7
        with:
          name: u-scope-linux
          path: build/source/u-scope

      - name: Upload Windows artifacts
        if: matrix.platforms.os == 'windows'
        uses: actions/upload-artifact@v7
        with:
          name: u-scope-win64
          path: u-scope-win64
