name: Build Application

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_call:
    inputs:
      skip_linter:
        description: 'Skip linter jobs'
        required: false
        type: boolean
        default: false

jobs:
  app-build-linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d06alexandrov/u-scope:0.6
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Linux Application
        run: |
          cmake -B build -G Ninja
          cmake --build build --config Release --target u-scope

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v7
        with:
          name: u-scope-linux
          path: build/source/u-scope

      - name: Upload cpp-linter files
        if: ${{ !inputs.skip_linter }}
        uses: actions/upload-artifact@v7
        with:
          name: cpp-linter-files
          path: |
            build/compile_commands.json
            build/**/*.h
            build/**/*.hpp

  app-build-windows:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d06alexandrov/u-scope:0.4-win
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Windows Application
        run: |
          # Create a directory Wine can own
          mkdir -p /tmp/wineprefix
          export WINEPREFIX=/tmp/wineprefix
          # Build
          cmake -B build -G Ninja
          cmake --build build --config Release --target u-scope
          cmake --install build --config Release --prefix $GITHUB_WORKSPACE/u-scope-win64

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v7
        with:
          name: u-scope-win64
          path: u-scope-win64

  cpp-linter:
    needs: app-build-linux
    if: ${{ !inputs.skip_linter }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d06alexandrov/u-scope:0.6
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download Compile Commands
        uses: actions/download-artifact@v7
        with:
          name: cpp-linter-files
          path: build

      - name: Install required packages
        run: |
          apt-get update
          apt-get install -y --no-install-recommends wget

      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@8e85cd02c8c3fe3ae527c94b5683fe2366b144ed # v2.20.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: '/usr/bin'
          style: ''
          tidy-checks: ''
          database: 'build'
          ignore: 'build'
          thread-comments: ${{ github.event_name == 'pull_request' }}
          step-summary: true
          lines-changed-only: ${{ github.event_name == 'pull_request' }}
          files-changed-only: ${{ github.event_name == 'pull_request' }}

  qml-linter:
    if: ${{ !inputs.skip_linter }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d06alexandrov/u-scope:0.6
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run QML Linter
        run: |
          cmake -B build -G Ninja
          cmake --build build --config Release --target all_qmllint
