name: Build Develop Image

on:
  push:
    branches: [ develop ]
    paths: 
      - '.devcontainer/Dockerfile'
      - '.devcontainer/Dockerfile.win'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-matrix.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .devcontainer/Dockerfile
            .devcontainer/Dockerfile.win

      - name: Create Matrix
        id: set-matrix
        run: |
          if [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            # If manual trigger, output both files explicitly
            JSON_FILES='[".devcontainer/Dockerfile", ".devcontainer/Dockerfile.win"]'
          else
            # If push trigger, use the output from the changed-files step
            JSON_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | jq -R -c 'split(" ")')
          fi
          echo "files=$JSON_FILES" >> $GITHUB_OUTPUT

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.files != '[]' && needs.detect-changes.outputs.files != ''
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-changes.outputs.files) }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Normalize Repository Name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Extract version from Dockerfile
        id: get_version
        run: |
          VERSION=$(grep 'LABEL version=' ${{ matrix.dockerfile }} | cut -d'"' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Tag is Unique
        run: |
          TAG_URL="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}"
          if docker manifest inspect $TAG_URL > /dev/null 2>&1; then
            echo "Version ${{ steps.get_version.outputs.VERSION }} already exists. Please increment the version in Dockerfile."
            exit 1
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.dockerfile }}
          target: base-img
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
