name: PR Agent (Gemini)

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    if: >
      github.event.sender.type != 'Bot' &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association))
      )
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: PR Agent action step
        uses: the-pr-agent/pr-agent@8e4d32e5497defd43c023a404f73560c62728961 # v0.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.ai_timeout: ${{ vars.GEMINI_AI_TIMEOUT }}
          config.model: "gemini/${{ vars.GEMINI_MODEL }}"
          config.fallback_models: '["gemini/${{ vars.GEMINI_FALLBACK_MODEL }}"]'
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
